version: "3.9"
services:
  web:
    image: nginx
    ports:
    - "8080:80"
    environment:
    - NNGINX_HOST=foobar.com
    - NGINX_PORT=80
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-CU12-ubuntu-20.04
    ports:
    - "1433:1433"
    environment:
    - SA_PASSWORD=Password
    - ACCEPT_EULA=Y
    - MSSQL_PID=Developer
